# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parcelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("superficie", models.FloatField(help_text="Superficie en hectares")),
                (
                    "localisation",
                    models.CharField(
                        help_text="Coordonnées GPS ou description géographique",
                        max_length=255,
                    ),
                ),
                (
                    "type_sol",
                    models.CharField(
                        help_text="Type de sol : argileux, sableux, limoneux...",
                        max_length=50,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Parcelle",
                "verbose_name_plural": "Parcelles",
                "db_table": "parcelles",
                "ordering": ["-date_creation"],
            },
        ),
    ]
