# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: blé, tomate, olivier", max_length=100
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CEREALE", "Céréale"),
                            ("LEGUME", "Légume"),
                            ("ARBRE", "Arbre fruitier"),
                            ("FOURRAGE", "Fourrage"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                (
                    "stade",
                    models.CharField(
                        choices=[
                            ("SEMIS", "Semis"),
                            ("GERMINATION", "Germination"),
                            ("CROISSANCE", "Croissance"),
                            ("FLORAISON", "Floraison"),
                            ("FRUCTIFICATION", "Fructification"),
                            ("RECOLTE", "Récolte"),
                            ("JACHÈRE", "Jachère"),
                        ],
                        default="SEMIS",
                        max_length=50,
                    ),
                ),
                ("date_plantation", models.DateField()),
                ("date_recolte_prevue", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
                "db_table": "cultures",
                "ordering": ["-date_plantation"],
            },
        ),
    ]
