# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cultures", "0001_initial"),
        ("parcelles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="culture",
            name="parcelle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cultures",
                to="parcelles.parcelle",
            ),
        ),
    ]
