# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("numero_serie", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TRACTEUR", "Tracteur"),
                            ("MOISSONNEUSE", "Moissonneuse-batteuse"),
                            ("DRONE", "Drone agricole"),
                            ("IRRIGATEUR", "Irrigateur"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                ("date_mise_service", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("EN_UTILISATION", "En utilisation"),
                            ("EN_PANNE", "En panne"),
                            ("EN_MAINTENANCE", "En maintenance"),
                            ("HORS_SERVICE", "Hors service"),
                        ],
                        default="DISPONIBLE",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
                "db_table": "machines",
                "ordering": ["nom"],
            },
        ),
    ]
