# Generated by Django 6.0.5 on 2026-05-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_initial'),
        ('parcelles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100)),
                ('moisture_level', models.FloatField(help_text='Soil moisture level (%)')),
                ('battery_level', models.FloatField(help_text='Sensor battery level (%)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_sensors', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'IoT Sensor',
                'verbose_name_plural': 'IoT Sensors',
                'db_table': 'iot_sensors',
            },
        ),
        migrations.CreateModel(
            name='IoTAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning')], default='CRITICAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='irrigation.iotsensor')),
            ],
            options={
                'verbose_name': 'IoT Alert',
                'verbose_name_plural': 'IoT Alerts',
                'db_table': 'iot_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
