# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IRRIGATION", "Irrigation"),
                            ("TRAITEMENT", "Traitement phytosanitaire"),
                            ("FERTILISATION", "Fertilisation"),
                            ("MECANISATION", "Mécanisation"),
                            ("RECOLTE", "Récolte"),
                            ("MAINTENANCE", "Maintenance machine"),
                            ("OBSERVATION", "Observation / diagnostic"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                ("date_planifiee", models.DateTimeField()),
                ("date_effective", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "À faire"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="A_FAIRE",
                        max_length=20,
                    ),
                ),
                ("compte_rendu", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
                "db_table": "interventions",
                "ordering": ["-date_planifiee"],
            },
        ),
    ]
