# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("interventions", "0001_initial"),
        ("parcelles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventions_creees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventions",
                to="machines.machine",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="parcelle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions",
                to="parcelles.parcelle",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="technicien",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TECHNICIEN"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interventions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
