# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Demande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AJOUT", "Ajout"),
                            ("MODIFICATION", "Modification"),
                            ("SUPPRESSION", "Suppression"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "objet",
                    models.CharField(
                        choices=[
                            ("PARCELLE", "Parcelle"),
                            ("CULTURE", "Culture"),
                            ("MACHINE", "Machine"),
                            ("INTERVENTION", "Intervention"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description détaillée de la demande"),
                ),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDEE", "Validée"),
                            ("REFUSEE", "Refusée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("motif_refus", models.TextField(blank=True, null=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Demande",
                "verbose_name_plural": "Demandes",
                "db_table": "demandes",
                "ordering": ["-date_envoi"],
            },
        ),
    ]
