# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("demandes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demande",
            name="admin_responsable",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "ADMIN"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_traitees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demande",
            name="farmer",
            field=models.ForeignKey(
                limit_choices_to={"role": "FARMER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
