# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CycleIrrigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_planifiee", models.DateTimeField()),
                ("date_debut_effective", models.DateTimeField(blank=True, null=True)),
                ("date_fin_effective", models.DateTimeField(blank=True, null=True)),
                ("volume_consomme_m3", models.FloatField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifié"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                            ("PROBLEME", "Problème signalé"),
                        ],
                        default="PLANIFIE",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Cycle d'irrigation",
                "verbose_name_plural": "Cycles d'irrigation",
                "db_table": "cycles_irrigation",
                "ordering": ["-date_planifiee"],
            },
        ),
        migrations.CreateModel(
            name="PlanIrrigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("GOUTTE_A_GOUTTE", "Goutte à goutte"),
                            ("ASPERSION", "Aspersion"),
                            ("SUBMERSION", "Submersion"),
                            ("AUTRE", "Autre"),
                        ],
                        default="GOUTTE_A_GOUTTE",
                        max_length=50,
                    ),
                ),
                (
                    "frequence_jours",
                    models.IntegerField(help_text="Fréquence d'irrigation en jours"),
                ),
                (
                    "duree_minutes",
                    models.IntegerField(help_text="Durée d'irrigation en minutes"),
                ),
                (
                    "heure_debut",
                    models.TimeField(help_text="Heure de début d'irrigation"),
                ),
                (
                    "volume_m3",
                    models.FloatField(help_text="Volume d'eau en m³ par cycle"),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Plan d'irrigation",
                "verbose_name_plural": "Plans d'irrigation",
                "db_table": "plans_irrigation",
            },
        ),
    ]
