# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("irrigation", "0001_initial"),
        ("parcelles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planirrigation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_irrigation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planirrigation",
            name="parcelle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_irrigation",
                to="parcelles.parcelle",
            ),
        ),
        migrations.AddField(
            model_name="cycleirrigation",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycles",
                to="irrigation.planirrigation",
            ),
        ),
        migrations.AddField(
            model_name="cycleirrigation",
            name="technicien",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TECHNICIEN"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cycles_irrigation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
