# Generated by Django 4.2.11 on 2026-05-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "FARMER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
